name: DQt tests

on:
  push:
    branches:
      - master
      - test
      - testqt6
  pull_request:
    branches:
      - master
      - test
      - testqt6

jobs:
  main:
    strategy:
      fail-fast: false

      matrix:
        platform: [ linux64, win64, osx64 ]
        dc: [ dmd-latest, dmd-2.100.0, ldc-latest, dmd-master ]

        include:
          - platform: linux64
            os: ubuntu-22.04
            model: 64
            qt_arch: gcc_64
            qtbase_url: 'https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_623/qt.qt6.623.gcc_64/'
            qtbase_file: '6.2.3-0-202201260729qtbase-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z'
            qticu_file: '6.2.3-0-202201260729icu-linux-Rhel7.2-x64.7z'

          - platform: win64
            os: windows-2022
            model: 64
            qt_arch: msvc2019_64
            qtbase_url: 'https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/qt6_623/qt.qt6.623.win64_msvc2019_64/'
            qtbase_file: '6.2.3-0-202201260729qtbase-Windows-Windows_10_21H2-MSVC2019-Windows-Windows_10_21H2-X86_64.7z'

          - platform: osx64
            os: macos-12
            model: 64
            qt_arch: macos
            qtbase_url: 'https://download.qt.io/online/qtsdkrepository/mac_x64/desktop/qt6_623/qt.qt6.623.clang_64/'
            qtbase_file: '6.2.3-0-202201260730qtbase-MacOS-MacOS_12-Clang-MacOS-MacOS_12-X86_64-ARM64.7z'

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Update PATH
        if: ${{ matrix.os == 'windows-2022' }}
        run: |
          echo "C:\msys64\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install libEGL
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        run: |
          sudo apt-get install -y libegl1

      - name: Install Qt
        run: |
          wget --no-verbose "${{ matrix.qtbase_url }}${{ matrix.qtbase_file }}"
          7z x "${{ matrix.qtbase_file }}" 6.2.3/${{ matrix.qt_arch }}/lib/ 6.2.3/${{ matrix.qt_arch }}/bin/ 6.2.3/${{ matrix.qt_arch }}/plugins/platforms

      - name: Install ICU for Qt
        if: ${{ matrix.qticu_file != '' }}
        run: |
          wget --no-verbose "${{ matrix.qtbase_url }}${{ matrix.qticu_file }}"
          7z x "${{ matrix.qticu_file }}"

      - name: 'Build & Test'
        run: |
          ${{ env.DC }} -run runtests.d --compiler=${{ env.DC }} -m${{ matrix.model }} --qt-path=6.2.3/${{ matrix.qt_arch }}
